### ISSUE TITLE
 The layer "sequential_1 has multiple inbound nodes, with different input shapes. Hence the notion of "input shape" is ill-defined for the layer. Use `get_input_shape_at(node_index)` instead.

### ISSUE THREAD

**Issue by naouss80** [farizrahman4u/qlearning4k#22]
Hi I seem to be running
`$ python test_catch.py`
and here is what I seem to get

Epoch 1000/1000 | Loss 0.0104 | Epsilon 0.10 | Win count 793
Traceback (most recent call last):
  File "test_catch.py", line 21, in <module>
    agent.play(catch)
  File "C:\Users\Naoussi Yvan\AppData\Local\Continuum\Anaconda3\lib\site-packages\qlearning4k-0.0.1-py3.6.egg\qlearning4k\agent.py", line 105, in play
  File "C:\Users\Naoussi Yvan\AppData\Local\Continuum\Anaconda3\lib\site-packages\qlearning4k-0.0.1-py3.6.egg\qlearning4k\agent.py", line 38, in check_game_compatibility
  File "C:\Users\Naoussi Yvan\AppData\Local\Continuum\Anaconda3\lib\site-packages\keras\engine\topology.py", line 1028, in input_shape
    ' has multiple inbound nodes, '
AttributeError: The layer "sequential_1 has multiple inbound nodes, with different input shapes. Hence the notion of "input shape" is ill-defined for the layer. Use `get_input_shape_at(node_index)` instead.

**Comment by jasperr** [comment]
I have seen the same error

**Comment by gaara100** [comment]
I'm having the same issue.

**Comment by jkempson** [comment]
Same. Looks like something changed in Keras?

**Comment by sdgroeve** [comment]
same here....

**Comment by vftens** [comment]
The same error.
Use
Keras==1.2.2
tensorflow==1.3.0
tensorflow-gpu==1.3.0
to avoid such error
